singleQuote: true
htmlWhitespaceSensitivity: strict
endOfLine: auto
printWidth: 120

overrides:
  - files: '*.scss'
    options:
      tabWidth: 4
  - files: '*.json'
    options:
      tabWidth: 4
  - files:
      - '*.html'
    options:
      tabWidth: 4
