// tslint:disable-next-line: one-variable-per-declaration

export const AppMetadata = {
  signupDesc: 'Simply Sign in to access all the features, today!',
  getmoreInfoDesc: 'Click below to get more information on how to become a BeeKee Professional.',
  signIn: 'Sign In',
  getmoreInfo: 'Get More Info',
  termsConditionHeader: 'By signing up, you"re agreeing to our',
  privacyPolicy: 'Privacy Policy',
  termsandCondition: 'Terms and Conditions',
  username: 'User Name',
  password: 'Password',
  usernamePwdValidation: 'Please enter UserName and Password',
  invalidUserNamePwd: 'Invalid UserName / Password',
  saveUsername: 'Save User Name And Password',
  forgotPassword: 'Forgot Password?',
  emailRequired: 'Email is required',
  invalidEmail: 'Enter a valid Email',
  passwordRequired: 'Password is required',
  forgotPasswordInfo:
    'Please enter email address you used when you signed up with BeeKee Pro to receive your password reset instructions.',
  reset: 'Reset',
  email: 'Email',
  resetPromptMsg: 'Verification sent.Please check your Email and enter the code to reset the password',
  resetPassword: 'Reset Password',
  newPassword: 'New Password',
  confirmNewPassword: 'Confirm New Password',
  confirmPasswordRequired: 'Confirm Password is required',
  validationPassword: 'Minimum 6 characters,at least one uppercase,one lowercase,one number and one special character',
  enterVerificationCode: 'Enter Verification Code',
  verificationCodeRequired: 'Verification Code is required',
  errorComparePasswordsValidation: 'New Password and Confirm New Password do not match',
  resetPasswordInfo: 'Please enter your new password below. Your new password must contain one alphanumeric character',
  userDoesNotExist: 'User with the specified email address does not exist',
  errorResetPassword: 'Incorrect verification code entered by the user',
  successResetPassword: 'Password Reset Successfully. Please try login with new password',
  successDownloadMessage: 'The PDF had been saved to ',
  letsGo: 'Let`s Go!',
  welcomeText: 'Welcome to your dashboard!',
  welcomeTextDesc: 'Get Started prospecting, connecting, quoting and much more!',
  exitAppMessage: 'Are you sure?',
  logoutMessage: 'Are you sure you want to logout?',
  becomeBeekeeProDesc:
    // tslint:disable-next-line: max-line-length
    'If you would like more information on how to list your business on BeeKee and take advantage of everything the BeeKee App has to offer please fill out the form below and a BeeKee associate will be in touch with you shortly.',
  firstNameStar: 'First Name *',
  lastNameStar: 'Last Name *',
  emailStar: 'Email *',
  phoneOptional: 'Phone (Optional)',
  cancel: 'Cancel',
  submit: 'Submit',
  successcontactUs: 'Thank you for contacting us. Our support team will contact you shortly',
  errorMessage: 'Some error, please try again later',
  requiredFirstName: 'Firstname is required',
  requiredLastName: 'Lastname is required',
  becomeBeekeePro: 'BECOME A BEEKEE PRO',
  phoneStar: 'Phone *',
  aptHash: 'Apt. #',
  zipCodeStar: 'Zip Code *',
  cityStar: 'City *',
  stateStart: 'State *',
  businessName: 'Business Name *',
  billaddress: 'Billing Address *',
  profileUpdateSuccess: 'Profile has been updated',
  profileUpdateError: 'Oops! Something went wrong',
};
